### ISSUE TITLE
Execution of Tests

### ISSUE THREAD

**Issue by tbergen1** [renuez/codecademy-tdd-gather-phase3#2]
After getting your project set up on my machine, I wasn't able to successfully run the tests. I kept running into some sort of permissions issue. Did you change some sort of dependency in the project?  I am able to run the solution code tests perfectly fine, so something must be different within your repo.  Here is a screenshot of what happened:

![permission failure](https://user-images.githubusercontent.com/8553822/49968670-7993ba00-fef4-11e8-8d19-734ead5a7d45.png)

**Comment by renuez** [comment]
I changed the ./bin and package.json to support CentOS/Mac for testing. 
I was on Windows 10 before.
I could not find the root cause with all abstractions of Git bash, Windows 10, ... down to wdio/mocha
e6174db 
Tests passed through successful.
