### ISSUE TITLE
Single Item API Not Present

### ISSUE THREAD

**Issue by tbergen1** [renuez/codecademy-tdd-gather-phase3#3]
In your index.js file under your routes folder, you seem to be missing a required new route that allows a user to find a single item by id.  This should look something like this:

```
router.get('/items/:id', async (req, res, next) => {
  const item = await Item.findById(req.params.id);
  res.render('single-item', {item});
});
```

**Comment by renuez** [comment]
Fixed with 2d7414e1d1176c882b4eecd41be69757135e2150, but was not push upstream.
